🍱asset:
- changed-files:
  - any-glob-to-any-file: 'public/**'
♻️ci:
- changed-files:
  - any-glob-to-any-file: '.github/**/*.yml'
⚙️config:
- changed-files:
  - any-glob-to-any-file: '*config.*'
📦dependencies:
- changed-files:
  - any-glob-to-any-file: ['bun.lockb', 'package.json', 'yarn.lock']
docker:
- changed-files:
  - any-glob-to-any-file: ['.dockerignore', 'Dockerfile']
📝documentation:
- changed-files:
  - any-glob-to-any-file: '**/*.md'
🚀enhancement:
- head-branch: ['^feature', 'feature', '^enhancement', 'enhancement']
✨feature:
- all:
  - changed-files:
    - any-glob-to-any-file: 'app/**'
    - all-globs-to-all-files: '!app/**/*.test.tsx'
🪸git:
- changed-files:
  - any-glob-to-any-file: ['.gitattributes', '.gitignore']
🧰infrastructure:
- changed-files:
  - any-glob-to-any-file: ['.devcontainer/*', '.editorconfig', 'biome.json', 'bunfig.toml', '.env*']
✅test:
- changed-files:
  - any-glob-to-any-file: ['happydom.ts', 'app/**/*.test.tsx']
🆚vscode:
- changed-files:
  - any-glob-to-any-file: '.vscode/*'
