name: 🎭 Playwright Tests

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request_target:
    paths:
      - "app/**"
      - "public/**"
      - "test/**"
      - ".dockerignore"
      - "auth.ts"
      - "bun.lock"
      - "Dockerfile"
      - "middleware.ts"
      - "package.json"
      - "*config.*"
  push:
    paths:
      - "app/**"
      - "public/**"
      - "test/**"
      - ".dockerignore"
      - "auth.ts"
      - "bun.lock"
      - "Dockerfile"
      - "middleware.ts"
      - "package.json"
      - "*config.*"
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  test:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ env.SHA }}
        env:
          SHA: ${{ github.event.pull_request.head.sha || github.sha }}

      - name: 🐣 Install bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: canary

      - name: 📦 Install dependencies
        run: bun i

      - name: 🔑 Generate Auth.js Secret
        run: bunx auth secret

      - name: 🧩 Build app
        run: bun run build

      - name: 🎭 Install Playwright Browsers
        run: bun playwright install --with-deps

      - name: 🧪 Run Playwright tests
        run: bun playwright test

      - name: 🆙 Upload Test Report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
